### ISSUE TITLE
有个BUG，就是在6.0上，点击这个泡泡，状态栏会变黑

### ISSUE THREAD

**Issue by ccwant** [Horrarndoo/GooView#1]
我的解决办法，在GooViewListener的构造方法中添加以下代码：
 mParams.flags =WindowManager.LayoutParams.FLAG_TRANSLUCENT_STATUS;
就可已解决沉浸式状态栏变黑的问题

**Comment by Horrarndoo** [comment]
嗯，谢谢指出，写这个demo的时候没有考虑到这一点

**Comment by Horrarndoo** [comment]
@CCwant 嗯，谢谢指出，写这个demo的时候没有考虑到这个点

**Comment by mexbo** [comment]
实测，6.0可以 ，是个不错的学习案例，Thanks~

**Comment by AutumnLight** [comment]
一楼的代码可以解决问题，非常感谢！
